#!/run/current-system/sw/bin/env bash

cd /home/Us0r/sources/hydra-test/
/home/Us0r/.nix-profile/bin/git fetch -a
/home/Us0r/.nix-profile/bin/git checkout -f origin/master
/run/current-system/sw/bin/nix flake update --commit-lock-file

LINUX_VERSION=./linux_version.nix
nix run .#packages.aarch64-linux.linux_version > $LINUX_VERSION
/home/Us0r/.nix-profile/bin/git add $LINUX_VERSION
/home/Us0r/.nix-profile/bin/git commit -m "update linux version"

/home/Us0r/.nix-profile/bin/git push origin HEAD:master
